#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := evpr-slave
EXTRA_COMPONENT_DIRS := $(PATH_COMPONENTS)

include $(IDF_PATH)/make/project.mk

