#define TAG "evpr_slave"
#define WIFI_SSID CONFIG_WIFI_SSID
#define WIFI_PWD CONFIG_WIFI_PASSWORD
#define DEVICE_IP CONFIG_DEVICE_IP
#define DEVICE_GATEWAY CONFIG_DEVICE_GATEWAY
#define DEVICE_NETMASK CONFIG_DEVICE_NETMASK
#define UDP_PKTSIZE CONFIG_UDP_PKT_SIZE
